baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'domus'
theme = 'hugo-book'
summaryLength = 35

[params]
    BookTheme = 'light'
    BookToC = true
    BookSection = '*'

[markup]
    [markup.goldmark.renderer]
        unsafe = true
