baseURL = 'https://domus.kosmolabs.org/'
languageCode = 'en-us'
title = 'domus'
theme = 'hugo-book'
summaryLength = 35
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
    BookTheme = 'light'
    BookToC = true
    BookSection = '*'

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2
